import type { Metadata } from "next";
import Aside from "@/components/common/Aside";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex bg-white rounded-tl-[200px] rounded-br-[80px]">
        <Aside />
        <div className="w-full">
            {children}
        </div>
    </div>
  );
}
